---
name: Talos worker image generation

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: { }

env:
  REGISTRY: ghcr.io
  INTEL_UCODE_VERSION: 20230808
  I915_UCODE_VERSION: 20230804
  NUT_CLIENT_VERSION: 2.8.0-v1.5.4
  ISCSI_TOOLS_VERSION: v0.1.4@sha256:3ab305068aa28513b26ab3c5b1f2937dbe3f63b9c50abe290287cc58eb454bb9

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest Talos release version
        id: talos-release
        run: |
          talos_release_tag=$(curl -sL https://api.github.com/repos/siderolabs/talos/releases/latest | jq -r ".tag_name")
          echo "talos_release_tag=$talos_release_tag" >> $GITHUB_OUTPUT
      
      - name: Fetch latest Talos release body
        id: talos-release-body
        run: |
          echo 'talos_release_body<<EOF' >> $GITHUB_OUTPUT
          curl -sL https://api.github.com/repos/siderolabs/talos/releases/latest | jq -r ".body" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Fetch latest Boot Asset release version
        id: boot-asset-release
        run: |
          boot_assets_release_tag=$(curl -sL https://api.github.com/repos/trosvald/talos-images/releases/latest | jq -r ".tag_name")
          echo "boot_assets_release_tag=$boot_assets_release_tag" >> $GITHUB_OUTPUT

      # Still need to decide if I want to download and expand the Release Asset instead for more stability
      - name: Compare release versions
        if: steps.talos-release.outputs.talos_release_tag != steps.boot-asset-release.outputs.boot_assets_release_tag
        id: compare-releases
        run: |
          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o /tmp/semver2.sh
          chmod +x /tmp/semver2.sh
          compare_result=$(/tmp/semver2.sh \
            ${{ steps.talos-release.outputs.talos_release_tag }} \
            ${{ steps.boot-asset-release.outputs.boot_assets_release_tag }})
          echo "compare_result=$compare_result" >> $GITHUB_OUTPUT
    outputs:
      newTalosReleaseFound: ${{ steps.compare-releases.outputs.compare_result }}
      talosReleaseTag: ${{ steps.talos-release.outputs.talos_release_tag }}
      talosReleaseBody: ${{ steps.talos-release-body.outputs.talos_release_body }}

  build-boot-assets:
    needs: [ check-releases ]
    if: needs.check-releases.outputs.newTalosReleaseFound
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/siderolabs/imager:${{ needs.check-releases.outputs.talosReleaseTag }}
      options: --privileged
      volumes:
        - /dev:/dev
    steps:
      - name: Build amd64 installer w/ addons
        run: |
          /bin/imager installer \
            --arch amd64 \
            --system-extension-image ghcr.io/siderolabs/intel-ucode:${{ env.INTEL_UCODE_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/nut-client:${{ env.NUT_CLIENT_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/i915-ucode:${{ env.I915_UCODE_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/iscsi-tools:${{ env.ISCSI_TOOLS_VERSION }} 

      - name: Build amd64 iso w/ addons
        run: |
          /bin/imager iso \
            --arch amd64 \
            --system-extension-image ghcr.io/siderolabs/intel-ucode:${{ env.INTEL_UCODE_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/nut-client:${{ env.NUT_CLIENT_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/i915-ucode:${{ env.I915_UCODE_VERSION }} \
            --system-extension-image ghcr.io/siderolabs/iscsi-tools:${{ env.ISCSI_TOOLS_VERSION }} \
            --extra-kernel-arg net.ifnames=0

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: talos-installer
          path: /out/metal-*-installer.tar
          if-no-files-found: error
          retention-days: 1

      - name: Upload iso artifact
        uses: actions/upload-artifact@v3
        with:
          name: talos-iso
          path: /out/metal-amd64.iso
          if-no-files-found: error
          retention-days: 1

  create-release:
    needs: [ check-releases, build-boot-assets ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build asset images
        uses: actions/download-artifact@v3
        with:
          name: talos-iso
          path: /tmp/talos-build-assets

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-releases.outputs.talosReleaseTag }}
          body: ${{ needs.check-releases.outputs.talosReleaseBody }}
          files: |
            /tmp/talos-build-assets/metal-amd64.iso

  push-container-image:
    needs: [ check-releases, build-boot-assets ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download build asset images
        uses: actions/download-artifact@v3
        with:
          name: talos-installer
          path: /tmp/talos-build-assets

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.10.0
        with:
          version: v0.11.2
          driver-opts: image=moby/buildkit:v0.12.0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: imjasonh/setup-crane@v0.3
      - name: Crane push installer
        run: |
          crane push --platform amd64 /tmp/talos-build-assets/metal-amd64-installer.tar ${{ env.REGISTRY }}/trosvald/installer-worker:${{ needs.check-releases.outputs.talosReleaseTag }}
